--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata: 
  name: EKS-Demo-Cluster
  region: ap-southeast-1
nodeGroups: 
  - 
    desiredCapacity: 2
    instanceType: t2.micro
    name: EKS-public-workers
  - 
    desiredCapacity: 1
    instanceType: t2.micro
    name: EKS-private-workers
    privateNetworking: true
vpc: 
  cidr: 192.168.0.0/16
  id: vpc-09ee0ce943b8c8d63
  subnets: 
    private: 
      ap-southeast-1a: 
        id: subnet-083e6c24a30ae4ed2
      ap-southeast-1b: 
        id: subnet-083e6c24a30ae4ed2
    public: 
      ap-southeast-1a: 
        id: subnet-04257581011106487
      ap-southeast-1b: 
        id: subnet-0684eb5ade0256973
