--- 
apiVersion: v1
kind: Service
metadata: 
  name: backend-service
spec: 
  ports: 
    - 
      nodePort: 31479
      port: 8080
      targetPort: 3000
  selector: 
    app: web
  type: NodePort
